/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as InboxImport } from './routes/inbox'
import { Route as GroupChatsImport } from './routes/group-chats'
import { Route as ChatsImport } from './routes/chats'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const InboxRoute = InboxImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRoute,
} as any)

const GroupChatsRoute = GroupChatsImport.update({
  id: '/group-chats',
  path: '/group-chats',
  getParentRoute: () => rootRoute,
} as any)

const ChatsRoute = ChatsImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsImport
      parentRoute: typeof rootRoute
    }
    '/group-chats': {
      id: '/group-chats'
      path: '/group-chats'
      fullPath: '/group-chats'
      preLoaderRoute: typeof GroupChatsImport
      parentRoute: typeof rootRoute
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chats': typeof ChatsRoute
  '/group-chats': typeof GroupChatsRoute
  '/inbox': typeof InboxRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chats': typeof ChatsRoute
  '/group-chats': typeof GroupChatsRoute
  '/inbox': typeof InboxRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/chats': typeof ChatsRoute
  '/group-chats': typeof GroupChatsRoute
  '/inbox': typeof InboxRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chats' | '/group-chats' | '/inbox'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chats' | '/group-chats' | '/inbox'
  id: '__root__' | '/' | '/chats' | '/group-chats' | '/inbox'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatsRoute: typeof ChatsRoute
  GroupChatsRoute: typeof GroupChatsRoute
  InboxRoute: typeof InboxRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatsRoute: ChatsRoute,
  GroupChatsRoute: GroupChatsRoute,
  InboxRoute: InboxRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/chats",
        "/group-chats",
        "/inbox"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/chats": {
      "filePath": "chats.tsx"
    },
    "/group-chats": {
      "filePath": "group-chats.tsx"
    },
    "/inbox": {
      "filePath": "inbox.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
